# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20170319_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlistitem',
            name='songlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='songs.SongList'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='songlistitem',
            name='song',
        ),
        migrations.AddField(
            model_name='songlistitem',
            name='song',
            field=models.ManyToManyField(to='songs.Song'),
        ),
    ]
